### PR TITLE
feature: add control-sqrt-not gate

### PR DESCRIPTION
**Pull request by unprovable**
Adding this gate makes things like CHSH circuits much more manageable off the bat.

*Issue #, if available:* - https://github.com/aws/amazon-braket-sdk-python/pull/297

*Description of changes:*

This edit to the schemas repo based on changes proposed in PR #297 on the sdk repo https://github.com/aws/amazon-braket-sdk-python/pull/297

*Testing done:*

Added unit test. More information available at: https://github.com/aws/amazon-braket-sdk-python/pull/297

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-schemas-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kshitijc — COMMENTED** [review]
Could we please add the corresponding unit tests here ?

**Comment by unprovable** [comment]
Fix: I added a basic test in line with the CY and CZ gates - there's nothing I can think for an extra test right now.

**Comment by unprovable** [comment]
Hello! Apologies, tracked down what I had forgotten to do and pushed a fix. All tests now succeed locally for me with `tox` (linters, docs, and unit-tests). Many thanks for your patience!

**Review by kshitijc — COMMENTED** [review]
Looks good! Could you please undo the changes to tox.ini so that we can merge these changes in?

**Comment by unprovable** [comment]
Done :) Would you like me to do the same for the`tox.ini` file in `amazon-braket-sdk-python` as well?

**Review by kshitijc — APPROVED** [review]

**Pull request merged**
